version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxi_shopper_api
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY} # Variável de ambiente com a chave da API do Google
    ports:
      - "8080:8080" # Mapeando a porta 8080  
    networks:
      - api_routes_network

networks:
  api_routes_network:
    driver: bridge