
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taxi_shopper_api
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY} # Variável de ambiente com a chave da API do Google
    ports:
      - "8080:8080" # Mapeando a porta 8080
    networks:
      - api_routes_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taxi_shopper_frontend
    ports:
      - "80:3000"
    depends_on:
      - api # Garantir que a API tenha iniciado antes de iniciar o frontend
    entrypoint: ["sh", "-c", "wait-for-it api:8080 -- serve "]
    restart: always
    networks:
      - api_routes_network


networks: 
  api_routes_network:
    driver: bridge
